In [1]:
import numpy as np
from scipy import stats
import pandas as pd

### 산술 평균 ###

In [2]:
# 성적의 평균 구하기
x = [70, 60, 80, 60, 50]
print(np.sum(x)/len(x))
print(np.mean(x))
print(np.array(x).mean())
print(pd.Series(x).mean())

64.0
64.0
64.0
64.0

### 조화 평균 ###

In [7]:
# 거리가 같을 때: 조화평균 (역수의 산술평균의 역수)
# 문제: 자동차가 60km를 60km/h로 이동하고, 같은 60km를 40km/h로 이동했을 때 평균 속도는?
x = np.array([60, 40])
print(len(x) / (1/60 + 1/40))
print(len(x) / np.sum(1/x))
print(round(stats.hmean(x),0))

47.99999999999999
47.99999999999999
48.0

In [4]:
# 상황: 두 생산 라인이 동일한 수의 제품(작업량)을 생산하지만, 
# 각 라인의 처리 속도가 다를 때 평균 처리 속도를 계산하기

# 라인 A: 60개/시간, 라인 B: 30개/시간
# → 동일 작업량(120개 제품 생산) 처리 시 평균 처리속도

x = np.array([60,30])
print(stats.hmean(x))

40.0

### 절사 평균 ###

In [9]:
# 월 평균이 3백만원이고 표준편차가 50만원인 정규 분포를 따르는 소득을 갖는 100명 생성
np.random.seed(0)
income = np.random.normal(3000000, 500000, 100) 
print(round(np.mean(income), 2))

3029904.01

In [10]:
# 월 소득이 1억원인 사람의 등장
# 100명의 소득이 300만원에 가까운데, 한 명 때문에 대표값인 평균이 약 400만원에 달함
income = np.append(income, 10**8) 
print(round(np.mean(income), 2))

3990003.97

In [11]:
stats.trim_mean(income, 0.2) # 하위 20%, 상위 80%를 제외하고 계산, 중앙 60%의 평균을 계산

np.float64(3031747.353015658)

### pandas로 대푯값 구하기 ###

In [12]:
import pandas as pd

data = pd.Series([60, 40, 60, 80, 50, 80])
print("평균값 : ", data.mean())
print("중앙값 : ", data.median())
print("최빈값 : ", data.mode())
print("최빈값 : ", data.mode().to_list())

평균값 :  61.666666666666664
중앙값 :  60.0
최빈값 :  0    60
1    80
dtype: int64
최빈값 :  [60, 80]

### 산포 통계 - 분산, 표준편차 등 계산 ###

#### 분산 계산 ####

In [13]:
x = [1, 2, 3, 4, 5]
print(np.var(x, ddof = 1)) # 분모 = n - 1 ( 5 - 1), 표본
print(np.array(x).var()) # 분모 = n
# 분모 = n , 자유도(ddof) 0:모분산인경우, 표본분산
print(pd.Series(x).var(ddof = 0))

2.5
2.0
2.0

#### 표준편차 계산 ####

In [14]:
x = [1, 2, 3, 4, 5]
print(np.std(x, ddof = 1))
print(np.array(x).std(ddof = 0))
print(pd.Series(x).std(ddof = 1))

1.5811388300841898
1.4142135623730951
1.5811388300841898

#### 변동계수의 필요성 ####
- 분산과 표준편차 모두 값의 스케일에 크게 영향을 받아 상대적인 산포를 보여주는데 부작합함.
- 변동 계수 = 표준편차 / 평균

In [15]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

print(np.std(x1, ddof = 1))
print(np.std(x2, ddof = 1))

1.5811388300841898
15.811388300841896

In [16]:
print(stats.variation(x1)) # 변동 계수
print(stats.variation(x2))

0.47140452079103173
0.4714045207910317

In [17]:
print(np.std(x1, ddof = 1) / np.mean(x1))
print(np.std(x2, ddof = 1) / np.mean(x2))

0.5270462766947299
0.5270462766947299

#### 스케일링 ####
- 둘 이상의 변수의 값을 상대적으로 비교할 때 사용

In [22]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

In [23]:
x1

array([1, 2, 3, 4, 5])

In [24]:
x2

array([10, 20, 30, 40, 50])

In [25]:
# Standard Scaling
z1 = (x1 - x1.mean()) / x1.std()
z2 = (x2 - x2.mean()) / x2.std()

print(z1)
print(z2)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

In [26]:
	
# Min-max Scaling
z1 = (x1 - x1.min()) / (x1.max() - x1.min())
z2 = (x2 - x2.min()) / (x2.max() - x2.min())

print(z1)
print(z2)

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]

In [27]:
# sklearn을 이용한 스케일링을 위한 데이터 준비
X = pd.DataFrame({"X1":[1, 2, 3, 4, 5],
    "X2": [10, 20, 30, 40, 50]})

X

   X1  X2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [ ]:
# scikit learn 의 MinMaxScaler 적용
# 0 ~ 1 데이터 스크케일링함
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() # 인스턴스화
Z = scaler.fit_transform(X) # fit_transform => ndarray # 이게 scikit에서 MinMax ??
pd.DataFrame(Z, columns=['X1', 'X2'])

     X1    X2
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00

In [29]:
# 표준 정규분포에 따라서 데이터의 수준을 맞춤
# 표준 정규분포 : 
from sklearn.preprocessing import StandardScaler